package plot.action;

public enum ActionType {
    KILL,
    HIRE_HITMAN,
    HIRE_THIEF,
    MOVE_TO_CITY,
    PROPOSE_TO,
    STEAL_PLACE,
    STEAL_ITEM,
    MUG,
    STEAL_VIOLENTLY_PLACE,
    CRAFT_ITEM,
    TRADE,
    BUY_ITEM,
    DISCREDIT_SOMEBODY,
    GIFT_SOMEBODY,
    CORRUPT_PLACE,
    HAVE_KID,
    HIDE,
    GO_TO_DUNGEON,
    GO_TO_TOMB,
    STUDY_MAGIC,
    RECRUIT_COLLEAGUE,
    RECRUIT_ACCOMPLICE,
    POSTULATE_TO_PATRON,
    SELL_ITEM,
    LISTEN
}
